apiVersion: v1
kind: Namespace
metadata:
  name: cloudmart-prod
  labels:
    app: cloudmart
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudmart-staging
  labels:
    app: cloudmart
    environment: staging
