# Argo Rollouts Helm values
# Install: helm install argo-rollouts argo/argo-rollouts \
#            -n argo-rollouts --create-namespace -f k8s/helm-values/argo-rollouts.yaml

controller:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi


dashboard:
  enabled: true
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
