# External Secrets Operator Helm values
# Install: helm install external-secrets external-secrets/external-secrets \
#            -n external-secrets --create-namespace -f k8s/helm-values/external-secrets.yaml
serviceAccount:
  create: true
  name: external-secrets-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::898865655202:role/cloudmart-external-secrets-role-staging

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Webhook for validation
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
