# KEDA Helm values
# Install: helm install keda kedacore/keda \
#            -n keda --create-namespace -f k8s/helm-values/keda.yaml
operator:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

metricsServer:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

podIdentityProviders:
  aws:
    enabled: true
