apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cloudmart-order-service-role-prod
