apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudmart-notification-secrets
  namespace: cloudmart-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudmart-notification-secrets
    creationPolicy: Owner
  data:
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: cloudmart/notification-service/staging
        property: SQS_QUEUE_URL
    - secretKey: FROM_EMAIL
      remoteRef:
        key: cloudmart/notification-service/staging
        property: FROM_EMAIL
