apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudmart-order-secrets
  namespace: cloudmart-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudmart-order-secrets
    creationPolicy: Owner
  data:
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: cloudmart/order-service/__ENV__
        property: SQS_QUEUE_URL
