apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cloudmart-notification-service-role-prod
