{{- $global := .Values.global | default dict }}
{{- $ns := $global.namespace | default (printf "cloudmart-%s" ($global.environment | default "prod")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ $ns }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  labels:
    app: product-service
